# Available languages with flags
LANGUAGES = {
    "en": "🇬🇧 English",
    "ru": "🇷🇺 Russian",
    "uz": "🇺🇿 Uzbek"
}

# Translations
TRANSLATIONS = {
    "en": {
        "welcome": "🌟 Welcome to SimpleLearn! Your AI Study Assistant 🌟\n\n✨ I'm here to help you learn smarter, not harder! ✨\n\n📚 What I can do for you:\n• 📄 Transform long lectures into concise summaries\n• 📝 Convert textbooks into key points\n• 📃 Break down complex articles into digestible chunks\n• 🎥 Extract key points from video lectures\n• 🎤 Transcribe and summarize audio recordings\n• 🔗 Summarize web articles and research papers\n• 💬 Condense long text passages\n\n🎯 Perfect for:\n• Students preparing for exams\n• Researchers reviewing literature\n• Anyone learning from long-form content\n\n🚀 Ready to start? Just share your content:\n• 📄 A document (lecture, textbook, paper)\n• 🎥 A video (lecture, tutorial)\n• 🎤 An audio recording\n• 🔗 A web link (article, research paper)\n• 💬 Some text\n\nI'll create a perfect summary for you!",
        "choose_language": "🌍 *Let's Get Started!*\n\n*Please select your preferred language:*\n\n🇬🇧 *English - Choose your language*\n🇷🇺 *Русский - Выберите ваш язык*\n🇺🇿 *O'zbek - Tilingizni tanlang*",
        "language_selected": "✅ Language selected successfully!",
        "processing": "🔄 Processing your document...",
        "processing_video": "🎥 Processing your video...",
        "transcribing": "🎤 Transcribing your audio...",
        "summarizing": "📝 Creating your summary...",
        "error": "❌ An error occurred. Please try again.",
        "unsupported": "❌ Unsupported file format. Please use PDF, DOCX, DOC, or TXT.",
        "send_document": "📤 Ready to Learn! 📤\n\n✨ Please share your content with me:\n• 📄 A document (lecture, textbook, paper)\n• 🎥 A video (lecture, tutorial)\n• 🎤 An audio recording\n• 🔗 A web link (article, research paper)\n• 💬 Some text\n\nI'll create a perfect summary for you!",
        "summary_ready": "✅ Your summary is ready! You can send me another document if you'd like to summarize more content.",
        "text_too_short": "⚠️ Text is too short. Please provide at least 50 characters.",
        "content_too_short": "⚠️ Content is too short. Please provide more content.",
        "file_too_large": "⚠️ File is too large. Please try a smaller file.",
        "memory_limit": "⚠️ System memory limit exceeded. Please try again later.",
        "processing_error": "❌ Error processing content. Please try again.",
        "no_text_found": "❌ No text found in the content. Please try a different file.",
        "settings": "⚙️ Settings",
        "current_language": "🌐 Current Language",
        "current_style": "📝 Current Summary Style",
        "language": "🌐 Language",
        "summary_style": "📝 Summary Style",
        "style_short": "Short",
        "style_medium": "Medium",
        "style_long": "Long",
        "premium_required": "💎 Premium feature. Please upgrade to access this feature.",
        "choose_style": "📝 Please select your preferred summary style:",
        "style_selected": "✅ Summary style updated successfully!",
        "text_successfully_processed": "Text Successfully Processed",
        "would_you_like_summary": "Would you like me to create a summary of this text?"
    },
    "ru": {
        "welcome": "🌟 Добро пожаловать в SimpleLearn! Ваш AI помощник в обучении 🌟\n\n✨ Я здесь, чтобы помочь вам учиться умнее, а не сложнее! ✨\n\n📚 Что я могу сделать для вас:\n• 📄 Преобразовать длинные лекции в краткие конспекты\n• 📝 Превратить учебники в ключевые моменты\n• 📃 Разбить сложные статьи на понятные части\n• 🎥 Извлечь ключевые моменты из видео лекций\n• 🎤 Расшифровать и обобщить аудио записи\n• 🔗 Обобщить веб-статьи и научные работы\n• 💬 Сократить длинные тексты\n\n🎯 Идеально подходит для:\n• Студентов, готовящихся к экзаменам\n• Исследователей, изучающих литературу\n• Всех, кто учится по длинным материалам\n\n🚀 Готовы начать? Просто поделитесь своим контентом:\n• 📄 Документ (лекция, учебник, статья)\n• 🎥 Видео (лекция, урок)\n• 🎤 Аудио запись\n• 🔗 Веб-ссылка (статья, научная работа)\n• 💬 Текст\n\nЯ создам для вас идеальный конспект!",
        "choose_language": "🌐 Пожалуйста, выберите предпочитаемый язык:",
        "language_selected": "✅ Язык успешно выбран!",
        "processing": "⏳ *Обработка вашего контента...* ⏳\n\n🔍 *Я внимательно анализирую ваш документ*\n⏱️ *Это может занять некоторое время, но оно того стоит!*",
        "summarizing": "🧠 *Создание вашего идеального резюме...* 🧠\n\n📊 *Анализ ключевых моментов*\n✨ *Определение основных идей*\n🎯 *Организация информации*\n\n*Почти готово!*",
        "error": "❌ *Упс! Что-то пошло не так* ❌\n\n😔 *Не удалось обработать ваш запрос*\n\n💡 *Попробуйте:*\n• Отправить другой документ\n• Проверить формат файла\n• Убедиться, что файл не слишком большой",
        "language": "🌐 Настройки языка",
        "settings": "⚙️ Настройки",
        "current_language": "Текущий язык:",
        "current_style": "Текущий стиль:",
        "summary_style": "📝 Стиль конспекта",
        "choose_style": "✨ *Выберите предпочитаемый стиль конспекта:*\n\nВыберите, насколько подробными должны быть ваши конспекты:",
        "style_short": "📌 Краткий (2-3 предложения)\nИдеально для быстрого обзора",
        "style_medium": "📋 Средний (4-6 предложений)\nСбалансированная детализация",
        "style_long": "📄 Подробный (7-10 предложений)\nПолное освещение темы",
        "style_selected": "✅ *Стиль конспекта обновлен!*\n\nВаши конспекты теперь будут в формате *{style}*.\n\nПопробуйте создать конспект, чтобы увидеть новый стиль в действии!",
        "too_large": "⚠️ *Превышен размер файла* ⚠️\n\n📏 *Документ больше 15МБ*\n\n💡 *Попробуйте:*\n• Сжать файл\n• Разделить на части\n• Использовать меньший документ",
        "unsupported": "⚠️ *Формат не поддерживается* ⚠️\n\n📝 *Я работаю с:*\n• PDF файлами (лекции, учебники)\n• DOCX документами (задания, заметки)\n• TXT файлами (учебные материалы)\n• Видео файлами (лекции, уроки)\n• Аудио файлами (записи, подкасты)\n• Веб-ссылками (статьи, работы)\n• Текстовыми сообщениями",
        "summary_title": "📋 *Резюме вашего документа* 📋",
        "transcribing": "🎤 *Транскрибирование аудио...* 🎤\n\n🎵 *Преобразование речи в текст*\n⏱️ *Это может занять несколько минут*",
        "processing_video": "🎥 *Обработка видео...* 🎥\n\n🎬 *Извлечение аудио*\n📝 *Преобразование в текст*\n⏱️ *Это может занять несколько минут*",
        "no_api_key": "⚠️ *Функция аудио/видео недоступна* ⚠️\n\n🔑 *Отсутствует API ключ*\n\n📞 *Пожалуйста, свяжитесь с администратором для включения этой функции*",
        "premium_required": "🔒 *Премиум функция*\n\nНастройки стиля конспекта доступны для премиум пользователей. Обновите свой аккаунт для доступа к этой и другим функциям!",
        "summary_ready": "✅ Ваш конспект готов! Вы можете отправить мне другой документ, если хотите создать еще один конспект.",
        "text_successfully_processed": "Text Successfully Processed",
        "would_you_like_summary": "Would you like me to create a summary of this text?"
    },
    "uz": {
        "welcome": "🌟 SimpleLearn'ga xush kelibsiz! Sizning AI o'quv yordamchingiz 🌟\n\n✨ Men sizga aqlli o'rganishda yordam beraman! ✨\n\n📚 Men nima qila olaman:\n• 📄 Uzoq ma'ruzalarni qisqa xulosalarga aylantiraman\n• 📝 Darsliklarni asosiy fikrlarga ajrataman\n• 📃 Murakkab maqolalarni tushunarli qismlarga bo'laman\n• 🎥 Video ma'ruzalardan asosiy fikrlarni ajratib olaman\n• 🎤 Audio yozuvlarni transkripsiya qilib xulosa qilaman\n• 🔗 Veb maqolalar va tadqiqot ishlarini xulosa qilaman\n• 💬 Uzoq matnlarni qisqartirib beraman\n\n🎯 Kimlar uchun foydali:\n• Imtihonlarga tayyorlanayotgan talabalar\n• Adabiyotni ko'rib chiqayotgan tadqiqotchilar\n• Uzoq matnlardan o'rganayotgan har kim\n\n🚀 Boshlashga tayyormisiz? Faqat kontentingizni yuboring:\n• 📄 Hujjat (ma'ruza, darslik, maqola)\n• 🎥 Video (ma'ruza, darslik)\n• 🎤 Audio yozuv\n• 🔗 Veb havola (maqola, tadqiqot ishi)\n• 💬 Matn\n\nMen siz uchun mukammal xulosa yarataman!",
        "choose_language": "🌐 Iltimos, tilni tanlang:",
        "language_selected": "✅ Til muvaffaqiyatli tanlandi!",
        "processing": "🔄 Hujjatingiz qayta ishlanmoqda...",
        "processing_video": "🎥 Videongiz qayta ishlanmoqda...",
        "transcribing": "🎤 Audiongiz transkripsiya qilinmoqda...",
        "summarizing": "📝 Xulosangiz yaratilmoqda...",
        "error": "❌ Xatolik yuz berdi. Iltimos, qayta urinib ko'ring.",
        "unsupported": "❌ Qo'llab-quvvatlanmaydigan fayl formati. Iltimos, PDF, DOCX, DOC yoki TXT formatidan foydalaning.",
        "send_document": "📤 O'rganishga tayyor! 📤\n\n✨ Iltimos, kontentingizni menga yuboring:\n• 📄 Hujjat (ma'ruza, darslik, maqola)\n• 🎥 Video (ma'ruza, darslik)\n• 🎤 Audio yozuv\n• 🔗 Veb havola (maqola, tadqiqot ishi)\n• 💬 Matn\n\nMen siz uchun mukammal xulosa yarataman!",
        "summary_ready": "✅ Xulosangiz tayyor! Agar yana xulosa qilmoqchi bo'lsangiz, menga boshqa hujjat yuborishingiz mumkin.",
        "text_too_short": "⚠️ Matn juda qisqa. Iltimos, kamida 50 ta belgi kiriting.",
        "content_too_short": "⚠️ Kontent juda qisqa. Iltimos, ko'proq kontent kiriting.",
        "file_too_large": "⚠️ Fayl juda katta. Iltimos, kichikroq fayl yuboring.",
        "memory_limit": "⚠️ Tizim xotirasi chegarasidan oshib ketdi. Iltimos, keyinroq qayta urinib ko'ring.",
        "processing_error": "❌ Kontentni qayta ishlashda xatolik. Iltimos, qayta urinib ko'ring.",
        "no_text_found": "❌ Kontentda matn topilmadi. Iltimos, boshqa fayl yuboring.",
        "settings": "⚙️ Sozlamalar",
        "current_language": "🌐 Joriy til",
        "current_style": "📝 Joriy xulosa uslubi",
        "language": "🌐 Til",
        "summary_style": "📝 Xulosa uslubi",
        "style_short": "Qisqa",
        "style_medium": "O'rta",
        "style_long": "Uzoq",
        "premium_required": "💎 Premium funksiya. Ushbu funksiyadan foydalanish uchun premium versiyaga o'ting.",
        "choose_style": "📝 Iltimos, xulosa uslubini tanlang:",
        "style_selected": "✅ Xulosa uslubi muvaffaqiyatli yangilandi!",
        "text_successfully_processed": "Matn muvaffaqiyatli qayta ishlandi",
        "would_you_like_summary": "Bu matnni xulosa qilishni xohlaysizmi?",
        "features": "📚 SimpleLearn quyidagi imkoniyatlarga ega:\n\n• Uzoq ma'ruzalarni qisqa xulosalarga aylantirish\n• Darsliklarni asosiy fikrlarga ajratish\n• Murakkab maqolalarni tushunarli qismlarga bo'lish\n• Video ma'ruzalardan asosiy fikrlarni ajratib olish\n\n🎯 Kontentni qayta ishlash:\n• Video va audio materiallarni xulosalash\n• Veb-sahifalarni tahlil qilish\n• Uzoq matnlarni qisqartirish\n\n👥 Foydalanuvchilar auditoriyasi:\n• Imtihonlarga tayyorlanayotgan talabalar\n• Adabiyotni ko'rib chiqayotgan tadqiqotchilar\n• Uzoq matnlardan o'rganayotgan har bir kishi",
        "summary_intro": "📚 SimpleLearn quyidagi imkoniyatlarga ega:\n\n• Uzoq ma'ruzalarni qisqa va aniq xulosalarga aylantirish\n• Darsliklardagi muhim fikrlarni ajratib ko'rsatish\n• Murakkab maqolalarni tushunarli qismlarga bo'lish\n• Video ma'ruzalardan asosiy fikrlarni olish\n• Audio yozuvlarni transkripsiya qilib xulosa qilish\n• Veb-maqolalar va tadqiqot ishlarini xulosalash\n\n📋 Kontent Turlari:\n• Hujjatlar (ma'ruzalar, darsliklar, maqolalar)\n• Videolar (ma'ruzalar, darsliklar)\n• Audio yozuvlar\n• Veb havolalar (maqolalar, tadqiqot ishlari)\n• Matnlar\n\n✨ SimpleLearn turli formatdagi kontentlarni qayta ishlashga qodir. Bu foydalanuvchilarga o'zlarining o'quv materiallarini turli manbalardan yuklash va xulosalar olish imkoniyatini beradi.",
        "summary_processing": "🔄 Xulosa yaratilmoqda...\n\n📝 Matn tahlil qilinmoqda\n✨ Asosiy fikrlar ajratilmoqda\n🎯 Xulosa shakllantirilmoqda",
        "summary_complete": "✅ Xulosa tayyor!\n\n📚 Quyidagi mavzular yoritildi:\n• Asosiy fikrlar\n• Muhim tushunchalar\n• Xulosa va natijalar",
        "summary_error": "❌ Xulosa yaratishda xatolik yuz berdi\n\nIltimos, quyidagilarni tekshiring:\n• Matn to'liqligi\n• Matn uzunligi\n• Matn formati\n\nKeyinroq qayta urinib ko'ring."
    }
}